@extends('layouts.dashboard', ['title' => 'My Progress | EduPulse AI'])

@section('content')
    <div class="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between">
        <div><p class="text-sm font-semibold text-cyan-600">Personal learning analytics</p><h1 class="mt-1 text-3xl font-semibold tracking-tight text-slate-950">My progress</h1><p class="mt-2 text-sm text-slate-500">See how your recorded performance and practice results change over time.</p></div>
        @if ($selectedSubject)<div class="flex flex-wrap gap-2" aria-label="Filter progress by subject">@foreach ($subjects as $subject)<a href="{{ route('student.progress', ['subject' => $subject->id]) }}" class="rounded-full px-3.5 py-2 text-xs font-semibold ring-1 transition {{ $selectedSubject->is($subject) ? 'bg-slate-950 text-white ring-slate-950' : 'bg-white text-slate-600 ring-slate-200 hover:ring-cyan-300 hover:text-cyan-700' }}">{{ $subject->code }}</a>@endforeach</div>@endif
    </div>

    @if ($selectedSubject)
        <section class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-5" aria-label="Progress summary">
            <x-metric-card label="Current grade" :value="$metrics['current_grade']" suffix="%" detail="Latest overall result" icon="trend" tone="indigo" />
            <x-metric-card label="Attendance" :value="$metrics['attendance']" suffix="%" detail="Latest snapshot" icon="calendar" tone="emerald" />
            <x-metric-card label="Practice average" :value="$metrics['quiz_average']" suffix="%" detail="Generated quizzes" icon="quiz" tone="cyan" />
            <x-metric-card label="Attempts" :value="$metrics['attempts']" detail="Completed practice quizzes" icon="check" tone="amber" />
            <x-metric-card label="Trend" :value="($metrics['trend'] > 0 ? '+' : '').$metrics['trend']" suffix=" pts" detail="Latest movement" icon="chart" :tone="$metrics['trend'] < 0 ? 'rose' : 'emerald'" />
        </section>

        <section class="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]">
            <article class="dashboard-panel p-5 sm:p-6"><div><h2 class="font-semibold text-slate-900">Academic performance</h2><p class="mt-1 text-xs text-slate-400">Quiz, assignment, activity, and attendance percentages</p></div><div data-chart-container class="mt-5 h-80"><canvas data-chart-config="{{ json_encode(['type' => 'line', 'labels' => $performanceChart['labels'], 'datasets' => [['label' => 'Quiz', 'data' => $performanceChart['quiz'], 'color' => 'cyan'], ['label' => 'Assignment', 'data' => $performanceChart['assignment'], 'color' => 'indigo'], ['label' => 'Activity', 'data' => $performanceChart['activity'], 'color' => 'amber'], ['label' => 'Attendance', 'data' => $performanceChart['attendance'], 'color' => 'emerald']]]) }}" aria-label="Line chart of your academic performance over time"></canvas></div></article>
            <article class="dashboard-panel p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h2 class="font-semibold text-slate-900">Focus topics</h2><p class="mt-1 text-xs text-slate-400">Repeated topics from analyses and quiz attempts</p></div><x-support-badge :level="$metrics['support_level']" /></div><div class="mt-5 space-y-3">@forelse ($weakTopics as $topic)<div class="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span class="text-sm font-medium text-slate-700">{{ $topic['topic'] }}</span><span class="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-slate-400 ring-1 ring-slate-200">{{ $topic['count'] }} signals</span></div>@empty<x-empty-state title="No focus topics" message="Topics needing review will appear after an analysis or practice quiz." />@endforelse</div></article>
        </section>

        <section class="dashboard-panel mt-6 p-5 sm:p-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-semibold text-slate-900">Practice quiz trend</h2><p class="mt-1 text-xs text-slate-400">Scores from quizzes grounded in your teacher's modules</p></div><a href="{{ route('student.quizzes.index', ['subject' => $selectedSubject->id]) }}" class="text-xs font-semibold text-indigo-600 hover:text-indigo-800">Open practice quizzes</a></div><div data-chart-container class="mt-5 h-72"><canvas data-chart-config="{{ json_encode(['type' => 'bar', 'labels' => $quizChart['labels'], 'datasets' => [['label' => 'Score', 'data' => $quizChart['values'], 'color' => 'violet']]]) }}" aria-label="Bar chart of your generated quiz scores"></canvas></div></section>

        <section class="mt-6 grid gap-6 xl:grid-cols-2">
            <article class="dashboard-panel overflow-hidden"><div class="border-b border-slate-100 px-5 py-5"><h2 class="font-semibold text-slate-900">Performance history</h2></div><div class="divide-y divide-slate-100">@forelse ($history as $performance)<div class="grid grid-cols-[1fr_auto] gap-4 px-5 py-4"><div><p class="text-sm font-semibold text-slate-700">{{ $performance->snapshot_date->format('M d, Y') }}</p><p class="mt-1 text-xs text-slate-400">Quiz {{ number_format((float) $performance->quiz_average, 0) }}% · Assignment {{ number_format((float) $performance->assignment_average, 0) }}% · Activity {{ number_format((float) $performance->activity_score, 0) }}%</p></div><span class="text-sm font-bold text-indigo-600">{{ number_format($performance->overall_grade, 1) }}%</span></div>@empty<div class="p-5"><x-empty-state title="No performance history" message="Teacher-recorded grade snapshots will appear here." /></div>@endforelse</div></article>
            <article class="dashboard-panel overflow-hidden"><div class="border-b border-slate-100 px-5 py-5"><h2 class="font-semibold text-slate-900">Practice history</h2></div><div class="divide-y divide-slate-100">@forelse ($attempts as $attempt)@php($percentage = (float) $attempt->max_score > 0 ? ((float) $attempt->score / (float) $attempt->max_score) * 100 : 0)<a href="{{ route('student.quizzes.results', $attempt) }}" class="flex items-center justify-between gap-4 px-5 py-4 transition hover:bg-slate-50"><div><p class="text-sm font-semibold text-slate-700">{{ $attempt->quiz->title }}</p><p class="mt-1 text-xs text-slate-400">{{ $attempt->completed_at->format('M d, Y · g:i A') }}</p></div><span class="rounded-lg px-3 py-2 text-sm font-bold {{ $percentage >= 75 ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ number_format($percentage, 0) }}%</span></a>@empty<div class="p-5"><x-empty-state title="No practice history" message="Complete a published quiz to begin tracking practice progress." /></div>@endforelse</div></article>
        </section>
    @else
        <section class="dashboard-panel mt-7 p-6"><x-empty-state title="No active enrollment" message="Your progress will become available after you are enrolled in an active subject." /></section>
    @endif
@endsection
