@extends('layouts.dashboard', ['title' => 'System Health | EduPulse AI'])

@section('content')
    @php($ready = $health['status'] === 'ok')
    <div><p class="text-sm font-semibold text-cyan-600">Operations</p><h1 class="mt-1 text-3xl font-semibold tracking-tight text-slate-950">System health</h1><p class="mt-2 text-sm text-slate-500">A safe operational summary with no credentials or secret values.</p></div>

    <section class="mt-7 rounded-2xl border p-6 {{ $ready ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50' }}">
        <div class="flex items-center gap-4"><span class="grid h-12 w-12 place-items-center rounded-full {{ $ready ? 'bg-emerald-600' : 'bg-amber-500' }} text-white"><x-icon :name="$ready ? 'check' : 'sparkles'" /></span><div><h2 class="font-semibold {{ $ready ? 'text-emerald-900' : 'text-amber-900' }}">{{ $ready ? 'EduPulse is ready' : 'EduPulse needs attention' }}</h2><p class="mt-1 text-sm {{ $ready ? 'text-emerald-700' : 'text-amber-700' }}">Checked {{ \Illuminate\Support\Carbon::parse($health['timestamp'])->format('M d, Y · g:i:s A') }}</p></div></div>
    </section>

    <section class="mt-6 grid gap-6 lg:grid-cols-2">
        <article class="dashboard-panel p-5 sm:p-6"><div class="flex items-start justify-between gap-4"><div><h2 class="font-semibold text-slate-900">Database</h2><p class="mt-1 text-xs text-slate-400">{{ $health['database']['connection'] }} connection · {{ $health['database']['latency_ms'] }} ms</p></div><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase {{ $health['database']['status'] === 'ready' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700' }}">{{ str_replace('_', ' ', $health['database']['status']) }}</span></div>@if (! empty($health['database']['missing_tables']))<div class="mt-5 rounded-xl bg-rose-50 p-4 text-xs leading-5 text-rose-700">Missing tables: {{ implode(', ', $health['database']['missing_tables']) }}</div>@elseif (! empty($health['database']['message']))<div class="mt-5 rounded-xl bg-rose-50 p-4 text-xs leading-5 text-rose-700">{{ $health['database']['message'] }}</div>@else<p class="mt-5 text-sm text-slate-500">The complete EduPulse schema is available.</p>@endif</article>
        <article class="dashboard-panel p-5 sm:p-6"><h2 class="font-semibold text-slate-900">Application</h2><dl class="mt-5 space-y-3 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-400">Environment</dt><dd class="font-medium text-slate-700">{{ $health['application']['environment'] }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-400">Framework</dt><dd class="font-medium text-slate-700">Laravel {{ $health['application']['laravel_version'] }}</dd></div><div class="flex justify-between gap-4"><dt class="text-slate-400">Diagnostic API</dt><dd><a href="{{ route('health') }}" class="font-semibold text-indigo-600 hover:text-indigo-800">/api/health</a></dd></div><div class="flex justify-between gap-4"><dt class="text-slate-400">Liveness probe</dt><dd><a href="/up" class="font-semibold text-indigo-600 hover:text-indigo-800">/up</a></dd></div></dl></article>
    </section>

    <section class="dashboard-panel mt-6 overflow-hidden"><div class="border-b border-slate-100 px-5 py-5 sm:px-6"><h2 class="font-semibold text-slate-900">Integration configuration</h2><p class="mt-1 text-xs text-slate-400">Configured means an endpoint or key is present; use each feature's own test for live connectivity.</p></div><div class="grid gap-px bg-slate-100 sm:grid-cols-3">@foreach (['gemini' => 'Gemini AI', 'ml_service' => 'ML classifier', 'rag_service' => 'PDF extraction'] as $key => $label)@php($integration = $health['integrations'][$key])<div class="bg-white p-5"><div class="flex items-center justify-between gap-3"><p class="text-sm font-semibold text-slate-800">{{ $label }}</p><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase {{ $integration['configured'] ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700' }}">{{ $integration['configured'] ? 'Configured' : 'Not configured' }}</span></div>@if ($key === 'gemini')<p class="mt-3 text-xs text-slate-400">{{ $integration['provider'] }} · {{ $integration['model'] }}</p>@endif</div>@endforeach</div></section>
@endsection
